### PR TITLE
UART and UDP Host

### PR DESCRIPTION
**Pull request by AbdouSam**
Hi, As you mentioned in the last PR, i created an abstract class to handle communication, i kept the args as they are and i added -i for interface to chose uart or udp.
I tested the code with my application that uses UDP interface it works fine.
The Code may need some optimizations, i might comeback to it in the future.

### CODE REVIEW

**Comment by camilstaps** [comment]
Thanks, you've done a great deal of work. Let me know when things are ready as far as you're concerned so that I can review the code :+1:

I'll close the previous PR in favour of this one.

**Comment by AbdouSam** [comment]
Hi, I tested the Code with my PIC32MZ MCU, and i was able to upload hex using this bootloader host.
I think i am done from my side, go ahead and review it. if there is any suggestion on how it could have been done better, please tell me, for learning purposes. Thank you.

**Comment by camilstaps** [comment]
I've cleaned up the code with some comments from `pylint`. Don't worry about this, there were probably also issues with my previous version, but please update your local version with my changes before continuing.

There are a few things I'd like to address before merging:

1. The class structure is somewhat odd, causing some code duplication. For instance the two implementations of `send_request` are almost identical. My idea was: put this general code in the parent class, and the specialised functionality (e.g. `self.soc.sendto(...)`) in the child class. From outside, the method called first should be that of the parent class, and the parent class should call the function in the child class. This is similarly the case for `read_response`.

1. As a side note for this, when a class extends another class, you don't need to explicitly say `super(...)`: instead of `super(UARTStream, self).process_read_response` you can use `self.process_read_response` as the method is inherited. But once you have changed as I suggested, it will be the parent calling the child anyway (instead of vice versa). In this direction you can also simply use `self`.

2. Once that is done, I'd suggest calling the method in the parent class `send_request` and `read_response`, and use other names in the child class.

3. Class methods should propagate and raise exceptions instead of handle them, so `UDPStream.read_response` should not `quit()` but `raise IOError` as in `UARTStream.read_response`.

4. Could you make the CRC table an option?

5. If you want, you can add yourself to the `__author__` and `__credits__` fields at the top of the file.

If anything is unclear do not hesitate to ask! Hopefully we can merge after these things have been addressed :rocket:

**Comment by AbdouSam** [comment]
Thanks for your feedback. 

I have noticed the annoying duplicate code too, and i have fixed this issue as you suggested. I have worked on the points you addressed. Also, thank you for the side note.

Please review the code, and tell me if anything needs to be fixed.

**Comment by camilstaps** [comment]
Thanks for addressing the suggestions, this is what I was looking for! I don't have a device with bootloader with me at the moment so I cannot test the serial part, but looking at the code the functionality shouldn't have changed :)

Thanks for the contribution :+1: :rocket:

**Pull request merged**
